#cloud-config

package_update: true
package_upgrade: true

packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - lsb-release
  - git

write_files:
  - path: /home/azureuser/docker-compose.yml.local
    content: |
${DOCKER_COMPOSE_CONTENT}
    owner: azureuser:azureuser
    permissions: '0644'

  - path: /home/azureuser/Caddyfile.local
    content: |
${CADDYFILE_CONTENT}
    owner: azureuser:azureuser
    permissions: '0644'

runcmd:
  # Install Docker
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
  - echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  - sudo apt-get update
  - sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin docker-compose
  
  # Add azureuser to docker group
  - sudo usermod -aG docker azureuser

  # Clone the Repository
  - cd /home/azureuser
  - git clone -b develop https://github.com/App-TDSE/Cardiotwin.git
  
  # Inject local configs
  - mv /home/azureuser/docker-compose.yml.local /home/azureuser/Cardiotwin/docker-compose.yml
  - mv /home/azureuser/Caddyfile.local /home/azureuser/Cardiotwin/Caddyfile
  - chown -R azureuser:azureuser /home/azureuser/Cardiotwin

  # Start the application
  - cd /home/azureuser/Cardiotwin
  - docker-compose up --build -d
