name: Simple Deploy to EC2

on:
  push:
    branches: [ main, develop ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            mkdir -p ~/app
            cd ~/app

            if [ ! -d ".git" ]; then
              git clone https://github.com/App-TDSE/Cardiotwin.git .
            fi

            git reset --hard
            git fetch origin
            git checkout ${{ github.ref_name }}
            git pull origin ${{ github.ref_name }}

            docker compose up --build -d

            docker image prune -f
